# Generated by Django 4.2.3 on 2023-08-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMPDEV', '0002_alter_maintainaces_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='gpu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='screen',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
