# Generated by Django 4.2.3 on 2023-08-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMPDEV', '0003_device_gpu_device_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
