# Generated by Django 4.2.3 on 2023-08-27 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EMPDEV', '0004_device_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='RamDevice',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='EMPDEV.ramdevice'),
        ),
        migrations.AlterField(
            model_name='device',
            name='StorgeDevice',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='EMPDEV.storgedevice'),
        ),
    ]
