# Generated by Django 4.2.3 on 2023-08-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMPDEV', '0006_alter_device_ramdevice_alter_device_storgedevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='cpu',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
